
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ama_dev
    ports:
      - "5432:5432"
    volumes:
      - ama_pg:/var/lib/postgresql/data
volumes:
  ama_pg:
